  export const imageCoverterKeywords = [
    "image converter", "JPG to PNG", "PNG to WebP", "image format conversion", "online converter",
    "image converter online", "free image converter", "convert image formats", "convert JPG to PNG", "convert PNG to JPG",
    "convert WebP to JPG", "convert JPG to WebP", "free image conversion", "image file converter", "convert PNG to WebP",
    "image size reducer", "image compression tool", "resize images online", "convert images fast", "high quality image conversion",
    "JPEG to PNG conversion", "convert images for free", "convert photos online", "photo to PNG", "photo to WebP", 
    "online image editing", "convert image with high quality", "high quality image converter", "image format change", 
    "image editing tool", "free photo converter", "convert image for website", "website image converter", "picture format converter",
    "image to PDF converter", "image to vector converter", "image resizer", "image compress online", "convert image file", 
    "image to PNG", "image to JPG", "image to WebP", "PNG to JPEG", "WebP to PNG", "image converter no watermark",
    "fast image converter", "convert multiple images", "bulk image converter", "image format support", "JPG to WebP converter",
    "free image tool", "convert photo to PNG", "convert photo to JPG", "convert photo to WebP", "compress image for web",
    "image compression for web", "web image converter", "convert graphics", "image to GIF converter", "GIF to JPG converter",
    "convert image for mobile", "image format optimizer", "convert pictures for print", "image format for Instagram",
    "image format for web", "JPEG to PNG", "free image resizer", "image optimization", "image compression free tool",
    "image conversion online tool", "photo converter app", "convert photos to any format", "convert files free", "convert image resolution",
    "image format for Facebook", "convert photos for email", "easy image conversion", "convert to WebP format",
    "convert photos fast", "online photo converter", "image file format change", "convert image without software", "JPG to BMP",
    "PNG to TIFF", "GIF to PNG", "TIFF to PNG", "PNG to BMP", "convert raster image", "convert vector image", "convert image for iPhone",
    "convert image for Android", "image file conversion site", "image format editor", "image format compression tool", 
    "convert photo to different formats", "convert image with high resolution", "convert photos fast and easy", "change image file type",
    "best image converter", "convert all image formats", "high resolution image converter", "convert images for free online",
    "convert image to different file types", "convert photo to high resolution", "photo editing tool", "resize image for website", 
    "convert image for social media", "convert PNG to JPG for free", "image format change tool", "photo converter no sign up",
    "online image format tool", "convert photo for Facebook", "convert picture format easily", "online image to PDF converter",
    "convert image free tool", "convert picture file size", "free online image editing", "online photo format converter", 
    "convert image to vector", "convert image for email", "convert photo without losing quality", "convert photos with no watermark",
    "image format tool", "convert PNG files to JPG", "image file format optimizer", "convert image in bulk", "image converter no signup",
    "convert images in seconds", "high quality image conversion tool", "image conversion without limits", "convert image quickly",
    "image file type changer", "convert files from PNG to JPG", "image format change tool online", "best free image converter",
    "image file compression and conversion", "image file optimization", "convert images and photos for free", "image compression service",
    "convert photo from one format to another", "PNG conversion tool", "JPG to WebP conversion", "convert large image files",
    "convert images without watermark", "convert files with ease", "convert photos in any format", "image format handling tool",
    "convert image resolution tool", "convert images to high resolution", "photo converter free tool", "best image compression",
    "convert files quickly", "compress and convert images", "image file optimization for web", "compress photos for mobile",
    "resize photo tool", "compress images for faster loading", "easy photo conversion", "photo file converter", "free file converter",
    "convert photos for social media", "convert file type online", "convert images for Instagram", "convert photos for Facebook",
    "free photo converter tool", "convert photo without software", "online photo file converter", "convert photos to high resolution"
  ];

    export const PDFkeywords = [
    "PDF converter", "PDF to DOCX", "PDF to Word", "convert PDF", "online PDF converter", 
    "free PDF converter", "PDF to editable Word", "convert PDF to DOCX free", "PDF file converter", 
    "PDF to Word converter", "PDF to text converter", "convert PDF to PPT", "convert PDF to Excel", 
    "PDF format converter", "free PDF to Word converter", "PDF to Word without losing formatting", 
    "convert PDFs fast", "convert PDFs online", "PDF to HTML converter", "convert PDF to image", 
    "convert PDF to JPG", "convert PDF to PNG", "convert scanned PDFs", "convert PDF to ePub", 
    "PDF to text", "convert PDF to ePub free", "PDF to RTF", "convert PDF to plain text", "convert PDF to spreadsheet", 
    "PDF file to Word", "PDF to Word with high quality", "PDF to Word online", "edit PDF online", "PDF file to Excel", 
    "convert PDF to editable text", "free PDF to Excel conversion", "convert PDF documents", "convert documents to Word", 
    "PDF to image converter", "PDF to JPG conversion", "convert image PDF to Word", "convert large PDF files", 
    "PDF to PowerPoint converter", "PDF to Word high quality", "PDF to Word easy conversion", "convert PDF to RTF free", 
    "PDF to CSV", "convert PDF to CSV online", "PDF to PDF/A", "PDF to Markdown", "convert PDF to rich text", 
    "convert PDFs to HTML", "free online PDF converter", "convert PDFs without registration", "convert image-based PDF", 
    "convert PDF to Word for free", "online PDF converter tool", "convert scanned PDF to Word", "convert PDF to PPTX", 
    "convert PDF to XLSX", "convert PDF to text online", "convert PDF to eBook", "PDF to eBook converter", 
    "convert PDF to Word without email", "PDF file to Word free", "free PDF to Word online", "convert PDF documents for free", 
    "convert large PDF files for free", "easy PDF to Word conversion", "PDF file to RTF free", "free PDF conversion tool", 
    "convert PDF for free online", "convert PDFs without software", "PDF to Word without software", "convert DOCX to PDF", 
    "convert PDF to DOCX for free", "convert PDFs quickly", "convert scanned documents to Word", "convert PDFs for Word",
    "free online PDF to Word", "convert file to PDF", "convert files to PDF", "convert DOCX to PDF", "convert image to PDF",
    "convert PDF to editable Word file", "convert PDF for eBooks", "convert scanned images to Word", "convert PDF to DOC", 
    "PDF to Word converter free tool", "convert large PDFs", "convert PDF files to readable Word", "convert PDFs instantly", 
    "convert PDFs on the go", "quick PDF to Word conversion", "convert PDF from URL", "convert PDF to ePub for free", 
    "convert PDFs from email", "best PDF to Word tool", "convert PDF to Word high speed", "convert PDF for print", 
    "convert PDF without registration", "convert PDF without software", "PDF to DOC online", "PDF to DOC without email", 
    "convert encrypted PDFs", "convert PDF to Word without hassle", "convert PDF files with high quality", "convert PDF for SEO", 
    "convert PDF to editable documents", "convert large PDFs to Word", "convert multiple PDFs at once", "bulk PDF converter", 
    "convert scanned PDFs to Word", "convert text-based PDF to Word", "PDF to Word with tables", "convert image-based PDF to Word free", 
    "convert PDF for mobile", "convert PDF to JPG images", "convert JPG PDF", "convert PDF to PPT free", "convert DOC to PDF", 
    "convert RTF to PDF", "convert PDF to image online", "convert PDF to Word format", "convert PDF to Word without changing layout", 
    "convert files into PDF format", "convert PDF to high quality Word", "convert PDF file with tables to Word", "convert scanned PDF", 
    "convert PDF to Word for documents", "convert PDF to Word no watermark", "convert PDFs with ease", "convert image PDF to text", 
    "easy PDF conversion", "convert PDFs with no software", "convert PDF for email", "convert Word to PDF", "convert PDF to Word for documents", 
    "convert document PDFs", "convert image to PDF free", "convert PDF without registration", "convert PDF format to Word", 
    "convert scanned documents", "convert files to PDF online", "PDF to Word converter easy", "free PDF converter no watermark", 
    "convert multiple PDFs to Word at once", "convert PDFs for print and Word", "bulk convert PDFs to Word", "best free PDF converter", 
    "fast PDF to Word conversion", "PDF to Word with accurate formatting", "convert PDF with all formatting intact", 
    "convert PDF to Excel sheet", "convert PDF files online free", "convert PDF file for eBook", "PDF document converter", 
    "convert PDF and maintain formatting", "free PDF to Word", "convert scanned PDF with OCR", "convert PDF with images", 
    "convert documents to PDF free", "convert PDF online for free", "convert PDF with tables intact", "convert PDF online fast", 
    "convert files to PDF easily", "convert PDF without email signup", "convert PDF from anywhere", "convert PDF without software"
  ];

    export const QRCodeKeywords = [
    "QR code generator", "QR code creator", "custom QR codes", "URL to QR code", "text to QR code",
    "QR code maker", "create QR code", "generate QR code", "QR code for websites", "QR code for email",
    "QR code for business cards", "generate custom QR codes", "QR code creator free", "QR code with logo",
    "QR code for social media", "QR code for URLs", "QR code for text", "generate QR code with logo",
    "QR code generator free", "QR code maker online", "free QR code generator", "customize QR code",
    "downloadable QR codes", "QR code for email addresses", "QR code customization", "QR code design",
    "QR code generator for text", "QR code for URLs free", "QR code for websites free", "QR code generator with logo",
    "dynamic QR codes", "static QR codes", "QR code for phone numbers", "QR code for WhatsApp", "generate QR codes for free",
    "QR code with custom color", "QR code for PDFs", "QR code for documents", "QR code for files", "generate QR codes with colors",
    "QR code for business", "QR code for payments", "QR code for apps", "QR code for marketing", "QR code for promotions",
    "QR code for campaigns", "QR code for coupons", "QR code for loyalty cards", "QR code for coupons free",
    "QR code for events", "QR code for ticketing", "QR code for online stores", "QR code for restaurant menus",
    "QR code for product packaging", "QR code for orders", "QR code for online services", "QR code generator tool",
    "QR code for coupons online", "QR code for discounts", "QR code for digital content", "QR code for video links",
    "QR code for event registration", "QR code for payments online", "QR code for sharing links", "QR code for information",
    "QR code generator website", "QR code for files online", "QR code generator download", "QR code generator with size customization",
    "QR code maker tool", "QR code creator online", "QR code creation", "QR code for customer engagement", "QR code for reviews",
    "QR code for product details", "QR code for locations", "QR code for feedback", "QR code for surveys", "QR code for reports",
    "QR code for personal use", "QR code for business use", "QR code with custom size", "QR code for tracking", 
    "QR code with custom shapes", "QR code for social sharing", "generate QR code with design", "create QR codes with logos",
    "QR code generator for emails", "generate QR code for payment", "create dynamic QR codes", "create static QR codes",
    "QR code to link", "QR code to text", "QR code to email", "QR code for sharing Wi-Fi", "QR code for contact details",
    "generate QR codes for text messages", "create QR codes for phone numbers", "QR codes for sharing business info", 
    "QR codes for business promotion", "QR code for loyalty programs", "QR code with different sizes", 
    "QR code with image", "QR code for tracking websites", "QR code with logo for websites", "generate QR codes with custom branding", 
    "QR codes for landing pages", "QR code to share event details", "QR code for free download", "custom QR code generator", 
    "QR code generator with design tools", "create free QR codes", "QR code for mobile app download", "QR code for sharing social media links", 
    "QR code for client engagement", "QR code for marketing purposes", "QR code for promotional campaigns", "QR code to link to website", 
    "QR code creator free tool", "generate QR codes for all purposes", "create QR codes for events", "QR codes for content sharing",
    "QR code generator for business cards", "QR code generator with customizable colors", "QR code with text message", 
    "QR code generator for social sharing", "QR code generator for media links", "QR code generator for photos", 
    "QR code generator to share links", "QR code for social media sharing", "QR code generator for photos", "QR code generator with customization options", 
    "QR code generation for text sharing", "QR code generator with multiple download formats", "QR code generator with customizable colors and sizes",
    "QR code generator for various platforms", "QR code generator for websites and URLs", "generate custom QR codes online", 
    "create professional QR codes online", "QR code generator for marketing tools", "QR code generator for customer engagement", 
    "QR code for multiple uses", "QR code for creating online content", "QR code for sharing media content", "generate professional QR codes", 
    "QR code for website engagement", "QR code for users to share information", "QR code for promoting business", "QR code generator for personal use"
  ];

      export const DocsKeywords = [
        "API documentation, file conversion API, QR code API, Convertly API, developer resources, file conversion, online file converter, API reference, convert PDF, convert images, API integration, API tutorial, developer documentation, QR code generation API, REST API, API reference guide, file conversion API documentation, Convertly developer tools, developer support, API guides, online converter integration, API docs, file conversion integration, image conversion API, PDF conversion API, documentation examples, web API, file API, generate QR codes, file API examples, API examples, file conversion API implementation, QR code API integration, online tools API, developer tools for file conversion, API tutorials, developer platform, file conversion service, QR code service API, QR code generation documentation, API features, API use cases, online converter API, API for developers, API support, API guides for developers, online API reference, conversion API docs, QR code service, image to PDF API, image format conversion API, PDF to image API, QR code for websites, create QR codes API, generate PDFs, QR code creation API, dynamic QR code API, custom QR code API, simple API for developers, easy-to-use file conversion API, QR code creation tools, file upload API, file download API, integrate API with web app, Convertly API for developers, conversion tools for developers, PDF converter API, image file converter API, QR code tools for websites, API integration for file conversion, user-friendly API, PDF to JPG API, convert document files API, document to image API, online file conversion API docs, online QR code API, API setup tutorial, code snippets for API integration, integration with Convertly API, API authentication guide, easy API integration, API documentation with examples, API best practices, scalable API solutions, server-side API, Convertly file converter API, API for content management, URL to QR code API, online file converter API integration, API for file management, file handling API, QR code integration API"
      ];